version: '3'

services:
  animals-rest:
    build: .
    image: animals-rest:latest
    environment:
      - MONGO_DB_URI=mongodb://admin:admin@mongo:27017/animals
      - MYSQL_DB_URI=mysql://admin:admin@mysql:3306/animals
    ports:
      - "3000:3000"
  test:
    image: animals-rest:latest
    command: npm run tests-production
    environment:
      - MONGO_DB_URI=mongodb://admin:admin@mongo:27017/animals
      - MYSQL_DB_URI=mysql://admin:admin@mysql:3306/animals
    depends_on:
      - mongo
      - mysql
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=animals
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=animals
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"

